steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
          echo "Cloning repository"
          git clone https://Juanfbl@bitbucket.org/juanfbl/test-app.git
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        ls
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'test-app/app_two'
    args: ['build', '-t', 'test-image:$BRANCH_NAME','.']